name: 'dbtga4'
version: '5.0.0'
config-version: 2
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbtga4:
    +materialized: view
    marts:
      +materialized: table

vars:
  current_day: "20230919"
  static_incremental_days: 3
  project: "shopkasatriavn"
  dataset: "analytics_274956178"
  start_date: "20230919" # Earliest date to load
  