name: 'ga4'
version: '5.0.0'
config-version: 2
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  ga4:
    +materialized: view
    marts:
      +materialized: table
  schema: schema1_20220730

vars:
  current_day: "20220730"
  static_incremental_days: 0
  project: "shopkasatriavn"
  dataset: "analytics_270502330"
  start_date: "20220730" # Earliest date to load
  end_date: "20220730"
  